version: '3.1'

services:

  webserver:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./web/:/usr/local/apache2/htdocs/
    networks:
      - classes-PSPI
networks:
    classes-PSPI:

