version: '3.1'

services:

  webserver:
    image: frontend:1.0
    build: ./web
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./web/:/usr/share/nginx/html
    networks:
      - classes-PSPI

networks:
    classes-PSPI:
      driver: bridge

